<!doctype html>
<html>
<head>
<title>Dispatch Blog</title>
<style>
html {
  font: normal 16px 'helvetica neue', sans-serif;
}
body {
  width: 100%;
  margin: 1rem 0;
}
@media screen and (min-width: 700px) {
  body {
    width: 700px;
    margin: 1rem auto;
  }
}
form > div {
  margin-bottom: .5rem;
}
form > div:after {
  content: '';
  display: block;
  clear: both;
}
label {
  float: left;
  width: 100px;
}
input[type="text"],
textarea {
  width: 500px;
  border: 1px solid #ddd;
}
textarea {
  height: 5.6rem;
}
label,
input[type="text"],
textarea {
  padding: .3rem;
}
input[type="submit"] {
  margin-left: 110px;
  padding: .8rem;
  border: 0;
  font-size: inherit;
  background: #9c0;
  color: #fff;
}
div.post {
  border-bottom: 3px solid #f0f0f0;
}
div.nav,
div.main {
  padding: 1rem;
}
</style>
</head>
<body>
<div class="nav">
  <a href="/index">Index</a> | <a href="/submit">New Post</a>
</div>
<div class="main"><?php echo $body; ?></div>
</body>
</html>
